/*
 * PhoneNumber API
 * Telco APIs built for a Java code test. This pretend company is called Oclet (Telco backwards)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liam.victor.murphy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.oclet.api.model;

import lombok.Builder;
import lombok.Getter;

import java.util.List;

/**
 * PhoneNumbers
 */

@Getter
@Builder
public class PhoneNumbers {
    private List<String> phoneNumbers;
}
